# Generated by Django 4.2.3 on 2023-08-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
