# Generated by Django 4.2.3 on 2023-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0002_candidate_education_candidate_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
