# Generated by Django 4.2.3 on 2023-08-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0003_alter_candidate_education_alter_candidate_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Portal_app.usermaster'),
        ),
        migrations.AlterField(
            model_name='company',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='Portal_app.usermaster'),
        ),
    ]
