# Generated by Django 4.2.3 on 2023-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0005_remove_company_city_company_aboutus_company_founded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='aboutus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
