# Generated by Django 4.2.3 on 2023-08-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0007_jobdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='Responsiblity',
            new_name='Responsiblities',
        ),
    ]
