# Generated by Django 4.2.3 on 2023-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0009_rename_responsiblities_jobdetails_jobskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Qualification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='Responsibilities',
            field=models.TextField(null=True),
        ),
    ]
