# Generated by Django 4.2.3 on 2023-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0011_alter_jobdetails_maxsalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
