# Generated by Django 4.2.3 on 2023-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0012_alter_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
