# Generated by Django 4.2.3 on 2023-08-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0014_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application',
        ),
    ]
