# Generated by Django 4.2.3 on 2023-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0016_alter_company_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(default='img/default/d1.png', upload_to='img/Company'),
        ),
    ]
