# Generated by Django 4.2.3 on 2023-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0017_alter_company_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(default='img/default/d2.png', upload_to='img/Company'),
        ),
    ]
