# Generated by Django 4.2.3 on 2023-08-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0018_alter_company_logo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(upload_to='Resume/')),
                ('Candidateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal_app.candidate')),
                ('Jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portal_app.jobdetails')),
            ],
        ),
    ]
