# Generated by Django 4.2.3 on 2023-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_app', '0019_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
